version: "3.9"

services:
  transfer-sh:
      command: '--provider local --port 8080'
      image: 'dutchcoders/transfer.sh:latest-noroot'
      container_name: 'transfer-sh'
      restart: unless-stopped
      environment:
        - BASEDIR=/data
      volumes:
        - transfer-sh:/data
      networks:
        - traefik

networks:
  traefik:
    external: true