version: "3.9"

services:
  transfer-sh:
    command: '--provider local'
    image: 'dutchcoders/transfer.sh:latest-noroot'
    container_name: 'transfer-sh'
    restart: unless-stopped
    environment:
      - BASEDIR=/data
      - PURGE_DAYS=366
      - PURGE_INTERVAL=24 # hours
      - MAX_UPLOAD_SIZE=50000000 # kb -> 50gb
      - RANDOM_TOKEN_LENGTH=12
    volumes:
      - transfer-sh:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transfer-sh.rule=Host(`transfer.${BASE_DOMAIN:-ozeliurs.com}`)"
      - "traefik.http.routers.transfer-sh.entrypoints=websecure"
      - "traefik.http.routers.transfer-sh.tls=true"
      - "traefik.http.routers.transfer-sh.tls.certresolver=cloudflare"
      - "traefik.http.services.transfer-sh.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true

volumes:
  transfer-sh:
    external: true